name: 'O Holding '
favicon: null
layout_spectrum: 0.1396388194989413
typography_spectrum: 0.5906015175860375
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#b1b9be'
    - '#edeef1'
    - '#3d3d3d'
    - '#6b6d6c'
    - '#0e0e0e'
  brandStrength: 0.9375
  lightness: 1
  saturation: 1
  rhythmicContrast: 0.25
purpose: []
