name: 'O Holding '
favicon: null
layout_spectrum: 0.1396388194989413
typography_spectrum: 0.5906015175860375
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.9161500085610896
  lightness: 0.7487780197989196
  saturation: 0.4207054867874831
  rhythmicContrast: 0.6612160722725093
purpose: []
